apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  # "admin" em base64
  POSTGRES_USER: YWRtaW4= 
  # "secretpass" em base64
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw==
  # "redispass" em base64
  REDIS_PASSWORD: cmVkaXNwYXNz